package View;

import Controller.CtrPersona;
import Model.Persona;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESTUDIANTE-14
 */
public class frmPersona extends javax.swing.JInternalFrame {

    public int idPersona = 0;

    public frmPersona() {
        initComponents();
        listarPersona();

        tabla_persona.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        btnEliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrPersona ctrPer = new CtrPersona();
                int seleccionarFila = tabla_persona.getSelectedRow();
                if (seleccionarFila != -1) {
                    Object id = tabla_persona.getValueAt(seleccionarFila, 0);
                    boolean res = ctrPer.eliminar(Integer.parseInt(id.toString()));
                    if (res) {
                        listarPersona();
                        JOptionPane.showMessageDialog(null, "Persona Eliminado");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Eliminar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No Se Selecciono persona.");
                }
            }
        });

        btnActualizar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int seleccionarFila = tabla_persona.getSelectedRow();
                if (seleccionarFila != -1) {
                    Object id = tabla_persona.getValueAt(seleccionarFila, 0);
                    Object codigo = tabla_persona.getValueAt(seleccionarFila, 1);
                    Object nombres = tabla_persona.getValueAt(seleccionarFila, 2);
                    Object apellidos = tabla_persona.getValueAt(seleccionarFila, 3);
                    Object direccion = tabla_persona.getValueAt(seleccionarFila, 4);
                    Object telefono = tabla_persona.getValueAt(seleccionarFila, 5);
                    Object correo = tabla_persona.getValueAt(seleccionarFila, 6);
                    idPersona = Integer.parseInt(id.toString());
                    txtCodigo.setText(codigo.toString());
                    txtNombre.setText(nombres.toString());
                    txtApellidos.setText(apellidos.toString());
                    txtDireccion.setText(direccion.toString());
                    txtCorreo.setText(correo.toString());
                    txtTelefono.setText(telefono.toString());
                } else {
                    JOptionPane.showMessageDialog(null, "No se Selecciono Persona.");
                }
            }
        ;
    }

    );
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_persona = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Formulario de Persona");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 24, -1, -1));

        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 24, -1, -1));

        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 24, -1, -1));

        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 65, -1, -1));

        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 65, -1, -1));

        jLabel6.setText("Correo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 118, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 21, 80, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 21, 124, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 21, 184, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 62, 279, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 62, 184, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 115, 279, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 21, 90, -1));

        btnActualizar.setText("Actualizar");
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 62, 90, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 103, 90, -1));

        tabla_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_persona);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, 773, 237));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Model
        Persona per = new Persona();
        //Controller
        CtrPersona crtPer = new CtrPersona();

        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Codigo");
        } else if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Nombres");
        } else if (txtApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Apellidos");
        } else if (txtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Direccion");
        } else if (txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Telefono");
        } else if (txtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Correo");
        } else {

            per.setCodigo(txtCodigo.getText());
            per.setNombres(txtNombre.getText());
            per.setApellidos(txtApellidos.getText());
            per.setDireccion(txtDireccion.getText());
            per.setTelefono(Integer.parseInt(txtTelefono.getText()));
            per.setCorreo(txtCorreo.getText());

            if (idPersona > 0) {
                //Actualizar
                per.setId_persona(idPersona);
                if (crtPer.actualizar(per)) {
                    idPersona=0;
                    this.listarPersona();
                    this.nuevo();
                    JOptionPane.showMessageDialog(null, "Se Actualizo Persona");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Actualizo Persona");
                }
            } else {
                //Registrar
                if (crtPer.Guardar(per)) {
                                                                                             this.listarPersona();
                    this.nuevo();
                    JOptionPane.showMessageDialog(null, "Se Guardo Persona");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar Persona");
                }
            }

        }

        //Guardar

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_persona;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void listarPersona() {
        CtrPersona ctrCat = new CtrPersona();
        List<Persona> per = ctrCat.listarPersona();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Codigo");
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Direccion");
        model.addColumn("Telefono");
        model.addColumn("Correo");

        for (Persona persona : per) {
            Object[] rowData = {
                persona.getId_persona(),
                persona.getCodigo(),
                persona.getNombres(),
                persona.getApellidos(),
                persona.getDireccion(),
                persona.getTelefono(),
                persona.getCorreo(),};
            model.addRow(rowData);
        }

        tabla_persona.setModel(model);
    }
    
    public  void nuevo() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }
    
}
