package View;

import Controller.CtrCategoria;
import Controller.ctrProductos;
import Model.Categoria;
import Model.ComboBoxItem;
import Model.Productos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class frmProductos extends javax.swing.JInternalFrame {

    public int idProducto = 0;

    public frmProductos() {
        initComponents();

        this.ListarCategoria();
        this.listarProductos();

        tabla_productos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Actualizar
        DefaultComboBoxModel<ComboBoxItem> model = (DefaultComboBoxModel<ComboBoxItem>) txtCategoria.getModel();
        btn_actualizar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int seleccionarFila = tabla_productos.getSelectedRow();
                Object id = tabla_productos.getValueAt(seleccionarFila, 0);
                Object codigo = tabla_productos.getValueAt(seleccionarFila, 1);
                Object descripcion = tabla_productos.getValueAt(seleccionarFila, 2);
                Object cantidad = tabla_productos.getValueAt(seleccionarFila, 3);
                Object marca = tabla_productos.getValueAt(seleccionarFila, 4);
                Object modelo = tabla_productos.getValueAt(seleccionarFila, 5);
                Object precio = tabla_productos.getValueAt(seleccionarFila, 6);
                Object stock = tabla_productos.getValueAt(seleccionarFila, 7);
                Object estado = tabla_productos.getValueAt(seleccionarFila, 8);
                Object id_categoria = tabla_productos.getValueAt(seleccionarFila, 9);

                idProducto = Integer.parseInt(id.toString());
                txtCodigo.setText(codigo.toString());
                txtDescripcion.setText(descripcion.toString());
                txtCantidad.setText(cantidad.toString());
                txtMarca.setText(marca.toString());
                txtModelo.setText(modelo.toString());
                txtPrecio.setText(precio.toString());
                txtStock.setText(stock.toString());
                if (estado.equals("Activo")) {
                    txtEstado.setSelected(true);
                } else {
                    txtEstado.setSelected(false);
                }
                for (int i = 0; i < model.getSize(); i++) {
                    ComboBoxItem comboBoxItem = model.getElementAt(i);
                    String comboBoxItemText = comboBoxItem.getValue();
                    if (comboBoxItemText.equals(String.valueOf(id_categoria))) {
                        txtCategoria.setSelectedIndex(i);
                        break;
                    }
                }

            }
        });

        //Eliminar
        btn_eliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ctrProductos ctrProd = new ctrProductos();
                int seleccionarFila = tabla_productos.getSelectedRow();
                Object id = tabla_productos.getValueAt(seleccionarFila, 0);
                boolean res = ctrProd.Eliminar(Integer.parseInt(id.toString()));
                if (res) {
                    JOptionPane.showMessageDialog(null, "Producto Eliminado");
                    listarProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "Eror al Eliminar Producto");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JComboBox<>();
        txtModelo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        txtEstado = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Formulario de Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 40, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 70, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modelo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 50, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stock:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Marca:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 40, 20));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, -1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 180, -1));

        getContentPane().add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 120, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 80, -1));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 180, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 180, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        getContentPane().add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, 30));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, 30));

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_productos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 620, 260));
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ctrProductos ctrProd = new ctrProductos();

        ComboBoxItem selectItem = (ComboBoxItem) txtCategoria.getSelectedItem();
        System.out.println("Valor seleccionado es: " + selectItem.getValue());
        Productos prod = new Productos();

        prod.setCodigo(txtCodigo.getText());
        prod.setDescripcion(txtDescripcion.getText());
        prod.setCantidad(Integer.parseInt(txtCantidad.getText()));
        prod.setMarca(txtMarca.getText());
        prod.setModelo(txtModelo.getText());
        prod.setPrecio(Double.parseDouble(txtPrecio.getText()));
        prod.setStock(Integer.parseInt(txtStock.getText()));
        prod.setId_categoria(Integer.parseInt(selectItem.getValue()));
        int estado = 0;
        if (txtEstado.isSelected()) {
            estado = 1;
        } else {
            estado = 0;
        }
        prod.setEstado(estado);

        if (idProducto == 0) {
            if (ctrProd.Guardar(prod)) {
                this.listarProductos();
                this.nuevo();
                JOptionPane.showMessageDialog(null, "Se Guardo Producto");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Guardar Producto");
            }
        } else {
            prod.setId_producto(idProducto);
            if (ctrProd.Actualizar(prod)) {
                this.listarProductos();
                this.nuevo();
                idProducto = 0;
                JOptionPane.showMessageDialog(null, "Se Actualizo Producto");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Actualizar Producto");
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JComboBox<ComboBoxItem> txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JRadioButton txtEstado;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    public void ListarCategoria() {
        CtrCategoria ctrCat = new CtrCategoria();
        List<Categoria> cat = ctrCat.listarCategoria();
        ArrayList<ComboBoxItem> items = new ArrayList<>();
        items.add(new ComboBoxItem("0", "Seleccionar"));
        for (Categoria categoria : cat) {
            int id = categoria.getId_categoria();
            String descripcion = categoria.getDescripcion();
            items.add(new ComboBoxItem(String.valueOf(id), descripcion));
        }
        DefaultComboBoxModel<ComboBoxItem> comboBoxModel = new DefaultComboBoxModel<>();
        for (ComboBoxItem item : items) {
            comboBoxModel.addElement(item);
        }
        txtCategoria.setModel(comboBoxModel);

    }

    public void listarProductos() {
        ctrProductos ctrProd = new ctrProductos();
        List<Productos> listProd = ctrProd.listarProductos();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Codigo");
        model.addColumn("Descripcion");
        model.addColumn("Cantidad");
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Precio");
        model.addColumn("Stock");
        model.addColumn("Estado");
        model.addColumn("Categoria");

        for (Productos productos : listProd) {
            String estado = "Inactivo";
            if (productos.getEstado() == 0) {
                estado = "Activo";
            }
            Object[] rowData = {
                productos.getId_producto(),
                productos.getCodigo(),
                productos.getDescripcion(),
                productos.getCantidad(),
                productos.getMarca(),
                productos.getModelo(),
                productos.getPrecio(),
                productos.getStock(),
                estado,
                productos.getId_categoria(),};
            model.addRow(rowData);
        }
        tabla_productos.setModel(model);

    }

    public void nuevo() {
        txtCodigo.setText("");
        txtDescripcion.setText("");
        txtCantidad.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtEstado.isSelected();
        this.ListarCategoria();
    }

}
